version: '3.9'

services:
  featurebase:
    build: .
    image: docker.io/featurebasedb/featurebase-simple
    ports:
     - "10101:10101"
    volumes:
      - "featurebase_simple:/featurebase"

volumes:
  featurebase_simple:
    driver: local

networks:
  default:
    name: fbnet
    external: true